export const DATA_TO_DO_LIST_START = 'DATA_TO_DO_LIST_START';
export const DATA_TO_DO_LIST_SUCCESS = 'DATA_TO_DO_LIST_SUCCESS';
export const DATA_TO_DO_LIST_FAILURE = 'DATA_TO_DO_LIST_FAILURE';

export const ADD_ITEM_TO_DO_LIST_START = 'ADD_ITEM_TO_DO_LIST_START';
export const ADD_ITEM_TO_DO_LIST_SUCCESS = 'ADD_ITEM_TO_DO_LIST_SUCCESS';
export const ADD_ITEM_TO_DO_LIST_FAILURE = 'ADD_ITEM_TO_DO_LIST_FAILURE';

export const DELETE_ITEM_TO_DO_LIST_START = 'DELETE_ITEM_TO_DO_LIST_START';
export const DELETE_ITEM_TO_DO_LIST_SUCCESS = 'DELETE_ITEM_TO_DO_LIST_SUCCESS';
export const DELETE_ITEM_TO_DO_LIST_FAILURE = 'DELETE_ITEM_TO_DO_LIST_FAILURE';

export const DONE_ITEM_TO_DO_LIST_START = 'DONE_ITEM_TO_DO_LIST_START';
export const DONE_ITEM_TO_DO_LIST_SUCCESS = 'DONE_ITEM_TO_DO_LIST_SUCCESS';
export const DONE_ITEM_TO_DO_LIST_FAILURE = 'DONE_ITEM_TO_DO_LIST_FAILURE';

export const SAVE_ITEM_TO_DO_LIST_START = 'SAVE_ITEM_TO_DO_LIST_START';
export const SAVE_ITEM_TO_DO_LIST_SUCCESS = 'SAVE_ITEM_TO_DO_LIST_SUCCESS';
export const SAVE_ITEM_TO_DO_LIST_FAILURE = 'SAVE_ITEM_TO_DO_LIST_FAILURE';

export const REMOVE_ALL_START = 'REMOVE_ALL_START';
export const REMOVE_ALL_SUCCESS = 'REMOVE_ALL_SUCCESS';
export const REMOVE_ALL_FAILURE = 'REMOVE_ALL_FAILURE';

export const REMOVE_ALL_DONE_START = 'REMOVE_ALL_DONE_START';
export const REMOVE_ALL_DONE_SUCCESS = 'REMOVE_ALL_DONE_SUCCESS';
export const REMOVE_ALL_DONE_FAILURE = 'REMOVE_ALL_DONE_FAILURE';
